<template>
  <div class="w-full h-full flex flex-col bg-white">
    <header class="view-header">
      <h1 class="text-xl text-gray-900">preview and debug</h1>
      <button class="p-1 text-blue-700 font-medium">
        <icon-save class="mr-[6px] text-base" />
        <span>long memories</span>
      </button>
    </header>
    <section class="flex-1">
      <!-- empty chat message -->
      <div v-if="messages.length === 0" class="text-center pt-48 space-y-2">
        <a-avatar :size="70" shape="square">A</a-avatar>
        <p class="text-gray-900 text-3xl font-bold">Chat bot</p>
      </div>

      <!-- chat messages -->
      <div v-else class="space-y-6 px-6 py-7">
        <chat-message
          v-for="(message, index) in messages"
          :key="index"
          :role="message.role"
          :content="message.content"
        />
        <!-- loading -->
        <ai-message v-if="isLoading" :is-loading="true" />
      </div>
    </section>

    <section class="py-4 shrink-0 space-y-3">
      <div class="px-9 flex items-center">
        <a-button class="mr-5 shrink-0" type="text" shape="circle" @click="clearMessages">
          <icon-brush class="text-base" />
        </a-button>
        <div
          class="h-12 pl-6 pr-5 flex items-center space-x-5 flex-1 rounded-3xl border border-gray-200"
        >
          <input
            class="flex-1 h-full outline-none text-sm"
            type="text"
            v-model="query"
            @keyup.enter="sendMessage"
          />
          <a-button class="mr-5 shrink-0" type="text" shape="circle">
            <icon-plus-circle class="text-base" />
          </a-button>
          <a-button class="mr-5 shrink-0" type="text" shape="circle" @click="sendMessage">
            <icon-send class="text-base" />
          </a-button>
        </div>
      </div>
      <p class="text-center text-xs text-gray-500">
        Content generated by ChatGPT may not be accurate or reliable.
      </p>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useRoute } from "vue-router";
import { Message } from "@arco-design/web-vue";
import ChatMessage from "./ChatMessage.vue";
import { debugApp } from "@/services/app-service";
import AiMessage from "./AiMessage.vue";

type Message = {
  role: "human" | "ai";
  content: string;
};

const messages = ref<Message[]>([]);
const query = ref<string>("");
const isLoading = ref(false);
const route = useRoute();

const sendMessage = async () => {
  if (!query.value) {
    Message.error("Please enter a question");
    return;
  }

  if (isLoading.value) {
    Message.warning("Please wait for the AI to respond");
    return;
  }

  const humanQuery = query.value;
  query.value = "";
  messages.value.push({
    role: "human",
    content: humanQuery,
  });

  try {
    isLoading.value = true;
    const result = await debugApp(route.params.id as string, humanQuery);
        
    if (isLoading.value) {
      messages.value.push({
        role: "ai",
        content: result.content,
      });
    }
    
  } finally {
    isLoading.value = false;
  }
};

const clearMessages = () => {
  messages.value = [];
  isLoading.value = false;
};
</script>

<style scoped lang="postcss">
.view-header {
  @apply w-full h-16 px-4 flex shrink-0 justify-between items-center border-b-[1px] border-gray-200;
}
</style>
